#!/bin/bash

tmux attach || (
	tmux new-session -d && \
	tmux set -g default-terminal screen-256color && \
	tmux split-window && \
	tmux kill-pane -t 0 && \
	tmux set -g status off && \
	tmux split-window -h -p 40 && \
	tmux split-window && \
	tmux select-pane -t 0 && \
	tmux attach)
